### ISSUE TITLE
mvn install fails : SNAPSHOT errors

### ISSUE THREAD

**Issue by jayunit100** [teiid/teiid-embedded-examples#37]
Running `mvn install` on these artifacts generally leads to failures.

Are these SNAPSHOT dependencies supposed to be used in the poms?  

```
[INFO] Building Teiid Examples excel-as-a-datasource 1.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.jboss.teiid:teiid-runtime:jar:9.0.0.Beta2-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.jboss.teiid:teiid-admin:jar:9.0.0.Beta2-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.jboss.teiid.connectors:translator-excel:jar:9.0.0.Beta2-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.jboss.teiid.connectors:connector-file:jar:9.0.0.Beta2-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.199 s
[INFO] Finished at: 2016-05-26T20:35:57-04:00
[INFO] Final Memory: 8M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project excel-as-a-datasource: Could not resolve dependencies for project org.jboss.teiid.examples:excel-as-a-datasource:jar:1.0.1-SNAPSHOT: The following artifacts could not be resolved: org.jboss.teiid:teiid-runtime:jar:9.0.0.Beta2-SNAPSHOT, org.jboss.teiid:teiid-admin:jar:9.0.0.Beta2-SNAPSHOT, org.jboss.teiid.connectors:translator-excel:jar:9.0.0.Beta2-SNAPSHOT, org.jboss.teiid.connectors:connector-file:jar:9.0.0.Beta2-SNAPSHOT: Could not find artifact org.jboss.teiid:teiid-runtime:jar:9.0.0.Beta2-SNAPSHOT -> [Help 1]
[ERROR]
```

**Comment by kylinsoong** [comment]
@jayunit100 this upstream repo compatible with upstream teiid, what I have plan create a separate branch for each Teiid release start from Teiid 9.0. So for current, if you want run example, build the upstream teiid

```
git clone git@github.com:teiid/teiid.git
cd teiid
mvn clean install -P release -Dmaven.javadoc.skip=true -s settings.xml
```

Edit `version.teiid` in teiid-embedded-examples/pom.xml, then try run example again

**Comment by jayunit100** [comment]
Ok thanks.  So, shouldn't it just point to published upstream snapshots or fall back to a snapshot that is resolvable?  

You're workaround is fine for now though.

**Comment by kylinsoong** [comment]
Teiid 9.0 will release in couples of weeks, by then I will release a compatible one.

**Comment by rareddy** [comment]
is there something that is version specific other than the dependency version?

**Comment by kylinsoong** [comment]
No, Jie has met the same issue, remove teiid dependencies' -SNAPSHOT, build will success.
I have plan to create a new branch each time teiid has a new final release, start from 9.0, for example,
the example 2.0 match to teiid 9.0, example 3.0 match to teiid 10.0, etc, do you think it's fine?

**Comment by rareddy** [comment]
We do not have to. If there is way we can pass the version number as a parameter to the "mvn " command that will do. If the examples itself are dependent on a specific version then we would need to branch them like when we went from EAP to WildFly. When a new translator is added we can write in the doc from which version it is available in README.MD file etc.

**Comment by kylinsoong** [comment]
Change readme as https://github.com/teiid/teiid-embedded-examples/pull/39, if you want build or run against a specific version, simple use `-Dversion.teiid=<teiid.version>`
