### ISSUE TITLE
Typo: Drools integration

### ISSUE THREAD

**Issue by rudygodoy** [teiid/teiid-embedded-examples#52]
There is a typo in the `HelloWorld.java` from Drools integration example. Specifically in:

https://github.com/teiid/teiid-embedded-examples/blob/master/drools-integration/src/main/java/org/teiid/example/drools/HelloWorld.java#L57

The typo doesn't break anything but it should probably read `fields` instead of `fileds`

**Comment by shawkins** [comment]
Thanks for pointing this out.
